### PR TITLE
SFStorefarm patch to correct  issue #5

### PR DESCRIPTION
**Pull request by matt6697**
Replaced ServicePort by Port in SFStorefarm to correct issue #5

### CODE REVIEW

**Comment by matt6697** [comment]
Hi Iain, did you have some time to review this pull request ? My tests have been done using Storefront 3.12 / Xendesktop 7.15 LTSR. Storefront SDK documentation confirms that the ServicePort variable doesn't exist anymore in [Get/Set-STFStoreFarm](https://citrix.github.io/storefront-sdk/Citrix.StoreFront.Stores/Get-STFStoreFarm/)

**Comment by iainbrighton** [comment]
Sure! I'm working away this week so will hopefully get a chance tomorrow. Work permitting ;)

**Comment by iainbrighton** [comment]
@matt6697 Do we know when this was changed? I assume Citrix didn't document this change anywhere?!

**Comment by matt6697** [comment]
I did the same research when writing the issue and couldn't find any old storefront SDK reference with the serviceport variable instead of the actual port one.

The port variable has been implemented from a least Storefront 3.6 as stated on @https://docs.citrix.com/en-us/storefront/3-6/sdk-overview.html page

```
# Add a Store that uses the new Authentication service configured to publish resources from the supplied servers

$store = Add-STFStoreService -VirtualPath $StoreVirtualPath -AuthenticationService $authentication -FarmName $Farmtype -FarmType $Farmtype -Servers $FarmServers -LoadBalance $LoadbalanceServers `

        -Port $Port -SSLRelayPort $SSLRelayPort -TransportType $TransportType
```

**Comment by iainbrighton** [comment]
It's been that way for a while then! We're still on 3.5 but not using this resource (yet!). Thanks @matt6697  for your contributions.

**Pull request merged**
